cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIASXSUMI76CXB2UJHA
      secret-key: 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
      
      
server:
  port: 8443     